# Generated by Django 3.2.10 on 2021-12-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLSite', '0002_auto_20211212_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
