# Generated by Django 3.2.10 on 2021-12-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLSite', '0004_auto_20211212_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cluster',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кластер'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='cluster',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кластер'),
        ),
    ]
