# Generated by Django 3.2.10 on 2021-12-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLSite', '0008_auto_20211212_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='vacancy_user',
            new_name='resume_user',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='highlighted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='vacancy',
            field=models.TextField(verbose_name='Вакансия'),
        ),
    ]
