# Generated by Django 3.2.10 on 2022-01-18 10:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('MLSite', '0010_remove_vacancy_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_user',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_user',
        ),
        migrations.AddField(
            model_name='resume',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
